# Flask build file 
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - checkout
#      - run: sudo apt install -y sqlite3
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: initialize database
          command: |
            . venv/bin/activate
            mkdir -p data/
            python manage.py db init
#            python manage.py db migrate
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
